# Generated by Django 4.1.2 on 2022-11-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stufs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuf', models.CharField(blank=True, max_length=100, verbose_name='stuf')),
                ('description', models.TextField(max_length=2000, verbose_name='description')),
                ('categories', models.TextField(blank=True, choices=[('other', 'разное'), ('electronics', 'электроника'), ('clothes', 'одежда'), ('for home', 'Для дома'), ('sports', 'спорт')], default='other', verbose_name='categories')),
                ('remainder', models.PositiveIntegerField(blank=True, verbose_name='remainder')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='price')),
            ],
        ),
    ]
