# Generated by Django 4.1.2 on 2022-12-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_stufs_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stufs',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='description'),
        ),
    ]
