# Generated by Django 4.1.2 on 2022-12-13 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_stufs_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stufs_in_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_stufs', models.PositiveIntegerField(verbose_name='amount_stufs')),
                ('stuf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stuf_key', to='webapp.stufs', verbose_name='stuf_key')),
            ],
        ),
    ]
