# Generated by Django 4.1.2 on 2022-12-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_stufs_in_cart_amount_stuf'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40, verbose_name='user')),
                ('numbers', models.CharField(max_length=50, verbose_name='numbers')),
                ('adress', models.CharField(max_length=50, verbose_name='numbers')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='date_c')),
                ('stufs', models.ManyToManyField(blank=True, related_name='stufs', to='webapp.stufs_in_cart', verbose_name='stufs')),
            ],
        ),
    ]
