# Generated by Django 4.1.2 on 2022-12-13 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promej',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='webapp.order', verbose_name='order')),
                ('stufs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Stufs', to='webapp.stufs', verbose_name='Stufs')),
            ],
        ),
    ]
