# Generated by Django 4.1.2 on 2022-12-13 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_promej'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stufs',
        ),
        migrations.AlterField(
            model_name='promej',
            name='stufs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stufs', to='webapp.stufs', verbose_name='stufs'),
        ),
    ]
