# Generated by Django 4.1.2 on 2022-12-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_remove_order_stufs_alter_promej_stufs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='adress',
            field=models.CharField(max_length=50, verbose_name='adress'),
        ),
    ]
